import type { Metadata } from "next";
import { InformationPage, PolicySection } from "@/components/information-page";
import { supportEmail } from "@/lib/site-config";

export const metadata: Metadata = {
  title: "Terms of Service | SupeQuote",
  description: "Terms for using SupeQuote estimate and quote software.",
};

export default function TermsPage() {
  return <InformationPage eyebrow="Legal · Terms" title="Terms of Service" updated="October 6, 2026">
    <PolicySection title="Agreement and operator"><p>These Terms are between you and Supe Digital, the operator of SupeQuote. SupeQuote is a SaaS product operated by Supe Digital, a business operating from Nigeria. In these Terms, “we”, “us”, and “our” refer to Supe Digital as the operator. By creating an account or using the service, you agree to these Terms. If you use SupeQuote for a business, you confirm that you are authorized to accept these Terms for that business.</p></PolicySection>
    <PolicySection title="Accounts and responsibility"><p>You must provide accurate account information and keep your sign-in credentials secure. You are responsible for activity under your account and should contact <a href={`mailto:${supportEmail}`}>{supportEmail}</a> promptly if you suspect unauthorized access.</p></PolicySection>
    <PolicySection title="The SupeQuote service"><p>SupeQuote currently provides estimate creation and history, estimate duplication, cost and pricing calculations, profit and margin calculations, recommended pricing, customer quote generation and public quote links, customer quote acceptance, company branding, and authentication. Features may change over time. SupeQuote does not provide team accounts, CRM, roof measurements, material ordering, invoicing, or payment collection inside the SaaS.</p></PolicySection>
    <PolicySection title="Plans and billing"><p>The Free plan is $0 per month and includes up to 3 estimates per month. Pro is $49 per month when billed monthly, or $468 per year when billed annually (equivalent to $39 per month). Plan features and prices shown when you subscribe form part of your purchase terms. Future plan or price changes will be communicated as appropriate and will not retroactively change a paid period.</p><p>Paid subscriptions renew for the selected billing period unless canceled before renewal. Cancellation stops future renewals; access generally continues through the paid period. If you buy through a payment provider, its checkout terms may also apply. See the <a href="/refund-policy">Refund &amp; Cancellation Policy</a> for details and refund requests.</p></PolicySection>
    <PolicySection title="Your data"><p>You retain responsibility for information you submit, including company details, estimates, quotes, and customer or property information. You must have the rights and permissions needed to enter and use that information, and you are responsible for its accuracy and for any notices required when collecting it. You are responsible for reviewing estimate inputs, calculations, prices, margins, and customer-facing quotes before relying on or sending them.</p></PolicySection>
    <PolicySection title="Acceptable use"><p>You may not use SupeQuote unlawfully, interfere with its operation or security, attempt unauthorized access, or misuse another person's information. We may restrict or suspend access when reasonably necessary to address misuse, security issues, or legal requirements.</p></PolicySection>
    <PolicySection title="Ownership and third-party services"><p>Supe Digital owns or has rights to SupeQuote, its software, name, branding, and service materials. These Terms do not transfer ownership of your submitted business information. SupeQuote relies on third-party services, including infrastructure providers, which may have their own terms and availability limitations.</p></PolicySection>
    <PolicySection title="Availability and warranty disclaimer"><p>We may update, change, or discontinue parts of the service. SupeQuote is provided as available, without a promise of uninterrupted access or specific business results. To the extent allowed by applicable law, we disclaim warranties except those that cannot legally be excluded.</p></PolicySection>
    <PolicySection title="Limitation of liability"><p>To the extent permitted by applicable law, Supe Digital is not liable for indirect, incidental, special, consequential, or punitive losses, or for lost profits, revenue, data, or business opportunities arising from use of the service. Nothing in these Terms limits liability that cannot legally be limited.</p></PolicySection>
    <PolicySection title="Suspension, termination, and changes"><p>You may stop using SupeQuote and cancel a paid subscription as described in the Refund &amp; Cancellation Policy. We may suspend or end access for a material breach, security concern, or legal requirement. We may update these Terms as the service changes; updated Terms will show a revised date and may be communicated where appropriate.</p></PolicySection>
    <PolicySection title="Governing law and questions"><p>These Terms are governed by the applicable laws of Nigeria, without regard to conflict-of-law principles. For questions about these Terms, email <a href={`mailto:${supportEmail}`}>{supportEmail}</a>.</p></PolicySection>
  </InformationPage>;
}
